### ISSUE TITLE
Projects 생성 권한 요청드립니다

### ISSUE THREAD

**Issue by hsung-yang** [yyu-nim/poseidonos-rtype#41]
메뉴에서 Actions 옆에 있는 Projects 메뉴를 사용해보고 싶습니다!
권한을 받을 수가 있을까요??

**Comment by hsung-yang** [comment]
위키랑 액션 수정 권한도 부탁드립니다!

**Comment by yyu-nim** [comment]
collaborator에 추가드렸습니다 혹시 그래도 권한 없다고 나오시면 꼭 알려주시길! 감사합니다 ㅎㅎ

**Comment by hsung-yang** [comment]
감사합니다!! 잘 됩니다 ㅎㅎ
